PR, bug and feature templates added
Gradiant/5g-images pull request #226
Opened 2024-01-16 11:44 UTC by jpontongradiant

2024-01-29 15:33 UTC, avrodriguezgrad requested changes

2024-01-29 15:33 UTC, avrodriguezgrad commented on .github/ISSUE_TEMPLATE/bugreport.yaml
> +        This form should only be used if _you can reporoduce_ the bug the in the latest version of openverso-images.
Change to 5g-images

2024-01-29 15:33 UTC, avrodriguezgrad commented on .github/ISSUE_TEMPLATE/bugreport.yaml
> +        should reproduce the issue on the most current release of openverso-images. Be sure to
Change to 5g-images

2024-01-29 15:33 UTC, avrodriguezgrad commented on .github/ISSUE_TEMPLATE/feature_request.yaml
> +description: Propose an enhancement to openverso-images
Change to 5g-images

2024-01-30 10:44 UTC, jpontongradiant commented on .github/ISSUE_TEMPLATE/bugreport.yaml
> +        should reproduce the issue on the most current release of openverso-images. Be sure to
Done

2024-02-09 10:21 UTC, avrodriguezgrad approved these changes

2024-02-09 10:22 UTC, merged